# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(X_list, censoring_list, B, rankmin_list, rankmax_list, step_size, lambda_1_all, lambda_2_all, penalty_factor, niter, linesearch_beta, eps, tol = 1e-10) {
    .Call(`_mrcox_test`, X_list, censoring_list, B, rankmin_list, rankmax_list, step_size, lambda_1_all, lambda_2_all, penalty_factor, niter, linesearch_beta, eps, tol)
}

compute_gradient <- function(X_list, censoring_list, rankmin_list, rankmax_list, B) {
    .Call(`_mrcox_compute_gradient`, X_list, censoring_list, rankmin_list, rankmax_list, B)
}

#' @export
compute_residual <- function(X_list, censoring_list, rankmin_list, rankmax_list, B) {
    .Call(`_mrcox_compute_residual`, X_list, censoring_list, rankmin_list, rankmax_list, B)
}

#' @export
compute_dual_norm <- function(grad, alpha, tol) {
    .Call(`_mrcox_compute_dual_norm`, grad, alpha, tol)
}

